language: node_js
node_js: 
  - "node"

sudo: false

cache:
  directories:
    - "node_modules"

before_script:
  - cp config/prod.env.js.dist config/prod.env.js

script:
  - npm run unit # Travis has no desktop environment so cannot run e2e in Chrome